### ISSUE TITLE
Loading additional models

### ISSUE THREAD

**Issue by sanivella** [spinscale/elasticsearch-opennlp-plugin#3]
Hi,
Thanks a lot for very useful plugin. 

I was trying to load additional models apart from person, date and location, then realized that plugin is coded to load only these models. 

Any plans to modify the code to support loading additional models?

Thanks
Sudhakar

**Comment by spinscale** [comment]
you can now load arbitrary models, see the README

**Comment by spinscale** [comment]
sorry, I closed this in the wrong repo... you can check out the ingest nlp plugin at https://github.com/spinscale/elasticsearch-ingest-opennlp - where this works
